version: '3.9'

services:
  auth-service:
    image: auth-service
    environment:
      USERS_SERVICE_URL: http://users-service:3000 

  users-service:
    image: users-service
    ports:
      - "3000:3000"