version: '3.9'

services:
  api-gateway:
    build:
      context: ../../
      dockerfile: deploy/composes/Dockerfile
    ports:
      - "80:3000"
    container_name: api-gateway
    # depends_on:
    #   - users-service
    #   - auth-service
    environment:
      - NODE_ENV=development

  # users-service:
  #   build:
  #     context: ../../../users-service
  #     dockerfile: deploy/composes/Dockerfile
  #   ports:
  #     - "3001:3000"
  #   container_name: users-service
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgres://user:password@db:5432/flowerdb

  # auth-service:
  #   build:
  #     context: ../../../auth-service
  #     dockerfile: deploy/composes/Dockerfile
  #   ports:
  #     - "3002:3000"
  #   container_name: auth-service
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgres://user:password@db:5432/flowerdb

  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: flowerdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: